export const apartmentData = [
  {
    id: 1,
    type: "Urban Studio",
    bedrooms: 0,
    bathrooms: 1,
    area: 450,
    floorPlanImage: "/page/home/studio-apartment.jpeg",
    price: 150000,
    url: "/apartments/1",
  },
  {
    id: 2,
    type: "City Retreat",
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    floorPlanImage: "/page/home/1-betroom-apartament.jpeg",
    price: 220000,
    url: "/apartments/2",
  },
  {
    id: 3,
    type: "Family Comfort",
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    floorPlanImage: "/page/home/2-betroom-apartament.jpeg",
    price: 350000,
    url: "/apartments/3",
  },
  {
    id: 4,
    type: "Executive Residence",
    bedrooms: 3,
    bathrooms: 2.5,
    area: 1250,
    floorPlanImage: "/page/home/3-betroom-apartament.jpeg",
    price: 450000,
    url: "/apartments/4",
  },
  {
    id: 5,
    type: "Skyline Penthouse",
    bedrooms: 4,
    bathrooms: 3,
    area: 1800,
    floorPlanImage: "/page/home/penthouse.jpeg",
    price: 750000,
    url: "/apartments/5",
  },
  {
    id: 6,
    type: "Luxury Suite",
    bedrooms: 3,
    bathrooms: 3,
    area: 1600,
    floorPlanImage: "/page/home/luxury-suite.jpeg",
    price: 650000,
    url: "/apartments/6",
  },
]
